// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nceoxebmdrcdqjcrwqgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jZW94ZWJtZHJjZHFqY3J3cWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTM3MjEsImV4cCI6MjA1OTkyOTcyMX0.He6yd6JORIzBseUhsi9WlkBkVeqG0Pz9VCzq1FOeQhM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);